spring:
  profiles:
    include:
    - jwt
    - oauth
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project1
    username: root
    password: 1234

  jpa:
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

logging:
  level:
    org.hibernate.type: trace
